name: Fast GitHub Pages deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: end-ea-5or/practice_pink
        with:
          folder: build
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}

