name: Fast GitHub Pages deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install, test and build
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: end-ea-5or/practice_pink
        with:
        folder: build # The folder the action should deploy.



